on: [pull_request]

jobs:
  analyze:
    runs-on: latest-ubuntu
    timeout-minutes: 1
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Upload SARIF file
        if: ${{ always() }}
        uses: actions/github-codeql-action/upload-sarif@v1
        with:
          sarif_file: canned-runs/sarif-results.json
